name: Databricks Dev Deploy

on:
    push:
        branches:
            - main

    workflow_dispatch:


jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_AUTH_TYPE: pat

        steps:
            - name: checkout_repo
              uses: actions/checkout@v4

            - name: setup databricks-cli
              uses: databricks/setup-cli@main

            - name: databricks bundle version
              run: databricks --version

            - name: databricks bundle validate
              run: databricks bundle validate

            - name: databricks bundle deploy
              run: databricks bundle deploy --target dev --auto-approve





